---
name: Serge3leo-temp-cola
channels:
  - conda-forge
dependencies:
  - python=3.12
  - blas
  - charset-normalizer
  - cmake
  - fortran-compiler
  - fortran-magic
  - lapack
  - meson
  - matplotlib
  - ninja
  - pillow
  - pip
  - pkgconfig
...
